champname = {0:"Anivia",
              1:"Kennen",
              2:"Renekton",
              3:"Shen",
              4:"Vayne",
              5:"Zed",
              6:"Riven",
              7:"Yasuo",
              8:"Jinx",
              9:"Karthus",
              10:"Ryze",
              11:"Akali",
              12:"Rumble",
              13:"Aatrox",
              14:"Ahri",
              15:"Brand",
              16:"Ezreal",
              17:"Fiora",
              18:"Fizz",
              19:"Kalista",
              20:"Katarina",
              21:"Veigar",
}

champdesc = {0:"A criofênix",
             1:"O Coração da Tempestade bate eternamente.",
             2:"Sangue e vingança.",
             3:"O olho não vê o medo, o ódio, o amor – e todas as coisas que perturbariam o equilíbrio.",
             4:"Não mato criaturas como você porque é certo. Mato porque eu gosto.",
             5:"Equilíbrio é a maestria dos tolos.﻿",
             6:"A espada de um guerreiro reflete a verdade em seu coração. A minha é sombria... e partida ao meio",
             7:"A morte é como o vento: está sempre ao meu lado.",
             8:"Explosivos voláteis são tudo que uma garota pode querer!",
             9:"A morte não é o fim da jornada, é apenas o começo...",
             10:"Tenham cuidado com esse mundo. O que está feito pode ser desfeito.",
             11:"Ter cara de perigoso e ser perigoso são coisas diferentes.",
             12:"Aff, vai demorar um tempão para limpar os restos do seu rosto da minha armadura!",
             13:"Minha missão é destruir até a esperança...",
             14:"As emoções humanas podem ser mais voláteis até do que a magia mais poderosa.",
             15:"Este lugar vai queimar, não pelas cinzas que voam ou o sopro do vento, mas pela vingança feita com minhas mãos.",
             16:"Se eu não conheço as regras, como posso estar desobedecendo?",
             17:"Eu busco sua morte em nome da honra. Embora você não tenha nenhuma, morrerá mesmo assim.",
             18:"Vocês não podem nem respirar na água. Que chatos.",
             19:"Hipócritas, infiéis e traidores… sintam nosso ódio.",
             20:"Nunca questione minha lealdade. Você jamais saberá o que eu aguento por ela.",
             21:"Você nega as trevas em sua alma...",
}

champlore = {0:"Anivia é um espírito alado e benevolente que suporta infinitos ciclos de vida, morte e renascimento para proteger Freljord. Uma semideusa nascida de ventos impiedosos e frios brutais, ela carrega esses poderes elementais para perseguir qualquer um que ousar perturbar sua terra natal. Anivia guia e protege as tribos do norte hostil, que a reverenciam como um símbolo de esperança e como uma portadora de grandes mudanças. Ela luta com todas as fibras do seu ser, sabendo que por meio do sacrifício, sua memória irá perdurar e ela renascerá em um novo amanhã.",
             1:"Mais do que um protetor rápido como um raio do equilíbrio ioniano, Kennen é o único yordle membro da Kinkou. Apesar da sua estatura pequena e peluda, ele anseia por ir contra qualquer ameaça com uma tempestade desenfreada de shurikens e entusiasmo sem limites. Ao lado de seu mestre, Shen, Kennen patrulha o reino dos espíritos, utilizando energia elétrica devastadora para abater seus inimigos.",
             2:"Renekton é um aterrorizante e furioso ser Ascendente dos desertos escaldantes de Shurima. Ele já foi o guerreiro mais estimado de todo o seu império, levando os exércitos da nação a inúmeras vitórias. No entanto, após a queda do império, Renekton foi enterrado nas areias e, lentamente, enquanto o mundo girava e mudava, ele sucumbia à loucura. Novamente liberto, ele é consumido pelo desejo de encontrar e matar seu irmão Nasus, a quem culpa pelos séculos que passou na escuridão graças à própria loucura.",
             3:"Para os guerreiros ionianos sigilosos conhecidos como Kinkou, Shen, o Olho do Crepúsculo, é um líder. Ele busca permanecer livre da confusão das emoções, preconceito ou ego, caminhando pelo caminho nunca visto do julgamento imparcial entre o reino dos espíritos e o mundo físico. Incumbido de impor harmonia entre os dois, Shen empunha lâminas de aço e energia arcana contra qualquer um que ameaçar o equilíbrio.",
             4:"Shauna Vayne é uma caçadora de monstros demaciana mortal e implacável que dedicou sua vida a encontrar e destruir o monstro que assassinou sua família. Armada com uma balestra em seu pulso e com um coração cheio de vingança, ela só é realmente feliz quando está matando praticantes ou criações das artes obscuras, atacando das sombras com um turbilhão de dardos de prata.",
             5:"Absolutamente impiedoso e implacável, Zed é o líder da Ordem das Sombras; uma organização criada com a intenção de militarizar as tradições marciais e mágicas de Ionia para expulsar os invasores noxianos. Durante a guerra, o desespero o levou a libertar a forma secreta das sombras, uma magia espiritual malévola tão perigosa e manipuladora quanto poderosa. Zed dominou todas essas técnicas proibidas para destruir qualquer coisa que considerasse uma ameaça a sua nação, ou a sua nova ordem.",
             6:"Outrora uma mestra das espadas nos esquadrões de Noxus, Riven agora é uma expatriada na terra que uma dia já tentou conquistar. Ela subiu nas posições do exército usando a força de sua convicção e eficiência brutal, e foi recompensada com uma lâmina rúnica lendária e seu próprio bando guerreiro. No entanto, no fronte ioniano, a fé de Riven em sua terra natal foi testada e, no fim, quebrada. Após cortar todos os laços com o império, ela agora busca seu lugar em um mundo devastado, mesmo ouvindo rumores de que a própria Noxus estava sendo reforjada...",
             7:"Yasuo, um ioniano extremamente determinado, é também um ágil espadachim que usa o próprio ar como arma para enfrentar seus inimigos. Quando jovem, ele teve seu orgulho ferido ao ser acusado injustamente do assassinato de seu mestre — sem conseguir provar sua inocência, ele foi forçado a matar o próprio irmão para se defender. Até hoje, mesmo depois do verdadeiro assassino do seu mestre ter sido revelado, Yasuo ainda não consegue se perdoar e vaga por sua terra natal com apenas o vento para guiar sua espada.",
             8:"Uma criminosa impulsiva e maníaca de Zaun, Jinx vive para disseminar o caos sem se preocupar com as consequências. Com um arsenal de armas mortais, ela detona as explosões mais altas e mais luminosas para deixar um rastro de destruição e pânico por onde passa. Jinx abomina o tédio e deixa alegremente sua marca caótica de pandemônio aonde quer que vá.",
             9:"Sendo o presságio do fim, Karthus é um espírito imortal cujas canções assombradoras são um prelúdio para o terror de sua aparição horripilante. Os vivos temem a eternidade dos mortos-vivos, mas Karthus vê apenas beleza e pureza em seu abraço, uma união perfeita de vida e morte. Quando Karthus emerge das Ilhas das Sombras, ele traz a alegria da morte aos mortais, como um apóstolo dos mortos-vivos.",
             10:"Considerado pela grande maioria como o mago mais habilidoso de Runeterra, Ryze é um arquimago ancião e amargo que carrega um enorme peso. Dotado de um enorme poder arcano e de uma notável estrutura física, ele busca incansavelmente pelas Runas Globais, que são fragmentos de magia pura que um dia criaram o mundo a partir do nada. Ele deve recuperar esses artefatos antes que eles caiam em mãos erradas, pois Ryze conhece bem os horrores que eles podem infligir em Runeterra.",
             11:"Abandonando a Ordem Kinkou e seu título de Punho das Sombras, Akali agora ataca sozinha, pronta para ser a arma mortal de que seu povo precisa. Embora mantenha tudo o que aprendeu com seu mestre Shen, ela se comprometeu a defender Ionia de seus inimigos, um assassinato de cada vez. Akali pode atacar em silêncio, mas sua mensagem será ouvida em voz alta e clara: temam a assassina sem mestre.",
             12:"Rumble é um jovem inventor irritadiço. Usando nada além de suas próprias mãos e uma pilha de sucata, o yordle briguento construiu um mecha colossal montado com um arsenal de arpões eletrificados e foguetes incendiários. Apesar de outros rirem de suas criações de ferro-velho, Rumble não se importa. Afinal, é ele que tem um cospe-fogo.",
             13:"Antes defensores honrados de Shurima contra o temido Vazio, Aatrox e sua raça no fim se tornaram uma ameaça ainda maior para Runeterra e a única coisa capaz de derrotá-los foi um tipo de feitiçaria mortal e traiçoeira. Mas após séculos de encarceramento, Aatrox foi o primeiro a encontrar a liberdade novamente, corrompendo e transformando qualquer tolo que tentasse empunhar a arma mágica que continha sua essência. Agora, com um corpo roubado, ele vaga por Runeterra transfigurado, em uma versão bizarra da sua forma anterior, buscando uma vingança apocalíptica.",
             14:"Com uma conexão inata com o poder latente de Runeterra, Ahri é uma vastaya capaz de transformar magia em orbes de pura energia. Ela gosta de brincar com suas presas manipulando suas emoções antes de devorar suas essências vitais. Apesar de sua natureza predatória, Ahri conserva um senso de empatia ao receber flashes de memória das almas que ela consome.",
             15:"A criatura conhecida como Brand já se chamou Kegan Rodhe, um aldeão da gélida Freljord, e é hoje uma lição das consequências que a tentação por poderes maiores pode trazer. Enquanto buscava uma das lendárias Runas Globais, Kegan traiu seus companheiros e a pegou para si e, em um instante, o homem já não existia mais. Com sua alma consumida pelo fogo e seu corpo um invólucro de uma chama viva, Brand agora vaga por Valoran em busca de outras Runas, jurando vingança por erros que ele nunca poderia ter sofrido em uma dúzia de vidas mortais.",
             16:"Um aventureiro arrojado, com um talento nato nas artes mágicas, Ezreal desbrava catacumbas soterradas, envolve-se com antigas maldições e supera com facilidade as situações mais improváveis. Sua coragem e ousadia não têm limites e ele prefere resolver as coisas no improviso, confiando parcialmente no seu talento, mas principalmente em sua mística luva shurimane, que ele usa para causar explosões arcanas devastadoras. Uma coisa é certa: quando Ezreal está por perto, lá vem problema. Ou lá vai. Ou já veio.",
             17:"A duelista mais temida de toda Valoran, Fiora é renomada tanto por suas maneiras bruscas e perspicácia quanto pela velocidade de sua rapieira de aço. Nascida na Casa Laurent no reino de Demacia, Fiora tomou o controle da família de seu pai no rastro de um escândalo que quase os destruiu. A reputação da Casa Laurent foi manchada, mas Fiora não mede esforços para restaurar a honra de sua família e devolvê-los a seu lugar de direito entre os melhores de Demacia.",
             18:"Fizz é um yordle anfíbio que vive entre os recifes que rodeiam as Águas de Sentina. É comum que ele busque e devolva os dízimos jogados no mar por capitães supersticiosos, mas mesmo o mais velho dos marinheiros sabe que não é uma boa ideia irritá-lo. São muitas as histórias daqueles que subestimaram seu caráter escorregadio. Frequentemente confundido com algum tipo de espírito marinho imprevisível, ele parece capaz de comandar enormes bestas das profundezas e se diverte confundindo tanto seus inimigos quanto seus aliados.",
             19:"Kalista, um espectro imortal de ira e retaliação, é um pesadelo perfurante que emerge das Ilhas das Sombras para punir enganadores e traidores. Os que foram traídos podem até chorar sangue para serem vingados, mas Kalista só atende àqueles dispostos a pagar com suas próprias almas. Mas quem quer que se torne o alvo de sua ira deve ir logo fazendo suas preces, pois os pactos firmados com essa sombria caçadora só terminam com o fogo cortante e gélido de sua lança espiritual.",
             20:"Decisiva em seus julgamentos e letal em combate, Katarina é a assassina de maior calibre de Noxus. Filha mais velha do lendário General Du Couteau, Katarina é reconhecida por seus assassinatos eficientes contra inimigos desavisados. Sua ambição ardente a levou a buscar alvos extremamente protegidos, mesmo correndo o risco de colocar seus aliados em perigo; mas não importa a missão, Katarina não hesita ao executar seu dever no meio de um furacão de adagas serrilhadas.",
             21:"Veigar, um yordle feiticeiro entusiasta, aceitou os poderes dos quais poucos ousaram se aproximar. Outrora um habitante de espírito livre de Bandópolis, ele desejava aprender mais sobre a magia celestial praticada pelos mortais, mas sua curiosidade natural foi distorcida ao ser aprisionado no Bastião Imortal. Ele agora é uma criatura teimosa com a fúria sombria das estrelas sob seu comando e é comumente subestimado por outros. E, apesar de Veigar acreditar que é maligno de verdade, há quem ainda questione suas verdadeiras e mais profundas motivações…",
}